#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_NAND_TCC) += nand_board_v8.o
obj-$(CONFIG_NAND_TCC) += nand_utils.o
obj-$(CONFIG_NAND_TCC) += nand_io_v8.o
obj-$(CONFIG_NAND_TCC) += tcc_nand_drv.o
obj-$(CONFIG_NAND_TCC) += tcc_nand.o
