#
# Copyright (c) 2016 Telechips, Inc.
# Telechips <Telechips@telechips.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_USB_DWC_OTG) += otgcore.o otgdev_io.o
obj-$(CONFIG_FWDN_V7) += fastbootusb.o
obj-$(CONFIG_FWDN_V7) += hsusb.o
obj-$(CONFIG_FWDN_V7) += usb_device.o
obj-$(CONFIG_FWDN_V7) += usb_manager.o
obj-$(CONFIG_FWDN_V7) += usbdev_class.o
obj-$(CONFIG_FWDN_V7) += usbphy.o
obj-$(CONFIG_FWDN_V7) += vtc.o


