#
# (C) Copyright 2016 Telechips, Inc.
#
# SPDX-License-Identifier:  GPL-2.0+  
#
obj-y		+= cpu.o
obj-y		+= clock.o
obj-y		+= tcc_ddr.o 
obj-y		+= lowlevel_init.o
obj-y		+= interrupts.o
obj-y		+= i2c.o
obj-y		+= tcc_usb.o
obj-y		+= tcc_cipher.o
