#
# Makefile for the U-boot SOC specific device drivers.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_TCC_SDHCI)		+= sdmmc/
obj-$(CONFIG_TCC_BOOT_SNOR)		+= snor/
obj-$(CONFIG_FWDN_V7)		+= fwdn/
