#=======================================================================================
#	FileName    : Makefile
#	Description : FWDN(FirmWare DownLoader) Makefile
#=======================================================================================
#
#	TCC Board Support Package
#	Copyright (c) Telechips, Inc.
#	ALL RIGHTS RESERVED
#
#=======================================================================================

obj-$(CONFIG_FWDN_V7) += fwdn_main.o
obj-$(CONFIG_FWDN_V7) += fwdn_drv_v7.o
obj-$(CONFIG_FWDN_V7) += fwdn_protocol_v7.o
#obj-$(CONFIG_FWDN_V7) += fwdn_nand.o 
obj-$(CONFIG_FWDN_V7) += fwdn_sdmmc.o
obj-$(CONFIG_FWDN_V7) += fwdn_snor.o
obj-$(CONFIG_FWDN_V7) += disk.o


#=======  end of file ==================================================================
