#
# Copyright (c) 2016 Telechips, Inc.
# Telechips <Telechips@telechips.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#


obj-$(CONFIG_USB_DWC3) += cli.o 
obj-$(CONFIG_USB_DWC3) += cli_intr.o
obj-$(CONFIG_USB_DWC3) += driver.o
obj-$(CONFIG_USB_DWC3) += pcd.o
obj-$(CONFIG_USB_DWC3) += pcd_hiber.o
obj-$(CONFIG_USB_DWC3) += pcd_intr.o
obj-$(CONFIG_USB_DWC3) += usb30dev.o
obj-$(CONFIG_USB_DWC3) += usb30reset.o

