#
# Copyright (c) 2016 Telechips, Inc
#
# SPDX-License-Identifier:      GPL-2.0+
#
#obj-$(CONFIG_LCD_AT070TN93) += lcd_at070tn93.o
#obj-$(CONFIG_LCD_ED090NA) += lcd_ED090NA.o
#obj-$(CONFIG_LCD_FLD0800) += lcd_FLD0800.o
